In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("googleplaystore.csv")
df.head()

App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1   
1                                Coloring book moana  ART_AND_DESIGN     3.9   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5   
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3   

  Reviews  Size     Installs  Type Price Content Rating  \
0     159   19M      10,000+  Free     0       Everyone   
1     967   14M     500,000+  Free     0       Everyone   
2   87510  8.7M   5,000,000+  Free     0       Everyone   
3  215644   25M  50,000,000+  Free     0           Teen   
4     967  2.8M     100,000+  Free     0       Everyone   

                      Genres      Last Updated         Current Ver  \
0               Art & Design   January 7, 2018               1.0.0   
1  Art & Design;Pretend Play  January 15, 2018               2.0.0   
2               Art & Design    August 1, 2018               1.2.4   
3               Art & Design      June 8, 2018  Varies with device   
4    Art & Design;Creativity     June 20, 2018                 1.1   

    Android Ver  
0  4.0.3 and up  
1  4.0.3 and up  
2  4.0.3 and up  
3    4.2 and up  
4    4.4 and up

In [3]:
df.shape

(10841, 13)

In [4]:
df.duplicated().sum()

483

In [5]:
df.drop_duplicates(inplace=True)

In [6]:
df.duplicated().sum()

0

In [7]:
df.isna().sum()

App                  0
Category             0
Rating            1465
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [8]:
df.drop("App", axis=1,inplace=True)


In [9]:
df.head()

Category  Rating Reviews  Size     Installs  Type Price  \
0  ART_AND_DESIGN     4.1     159   19M      10,000+  Free     0   
1  ART_AND_DESIGN     3.9     967   14M     500,000+  Free     0   
2  ART_AND_DESIGN     4.7   87510  8.7M   5,000,000+  Free     0   
3  ART_AND_DESIGN     4.5  215644   25M  50,000,000+  Free     0   
4  ART_AND_DESIGN     4.3     967  2.8M     100,000+  Free     0   

  Content Rating                     Genres      Last Updated  \
0       Everyone               Art & Design   January 7, 2018   
1       Everyone  Art & Design;Pretend Play  January 15, 2018   
2       Everyone               Art & Design    August 1, 2018   
3           Teen               Art & Design      June 8, 2018   
4       Everyone    Art & Design;Creativity     June 20, 2018   

          Current Ver   Android Ver  
0               1.0.0  4.0.3 and up  
1               2.0.0  4.0.3 and up  
2               1.2.4  4.0.3 and up  
3  Varies with device    4.2 and up  
4                 1.1    4.4 and up

In [10]:
df["Category"].unique()

array(['ART_AND_DESIGN', 'AUTO_AND_VEHICLES', 'BEAUTY',
       'BOOKS_AND_REFERENCE', 'BUSINESS', 'COMICS', 'COMMUNICATION',
       'DATING', 'EDUCATION', 'ENTERTAINMENT', 'EVENTS', 'FINANCE',
       'FOOD_AND_DRINK', 'HEALTH_AND_FITNESS', 'HOUSE_AND_HOME',
       'LIBRARIES_AND_DEMO', 'LIFESTYLE', 'GAME', 'FAMILY', 'MEDICAL',
       'SOCIAL', 'SHOPPING', 'PHOTOGRAPHY', 'SPORTS', 'TRAVEL_AND_LOCAL',
       'TOOLS', 'PERSONALIZATION', 'PRODUCTIVITY', 'PARENTING', 'WEATHER',
       'VIDEO_PLAYERS', 'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION',
       '1.9'], dtype=object)

In [11]:
df[df["Category"]=="1.9"]

Category  Rating Reviews    Size Installs Type     Price Content Rating  \
10472      1.9    19.0    3.0M  1,000+     Free    0  Everyone            NaN   

                  Genres Last Updated Current Ver Android Ver  
10472  February 11, 2018       1.0.19  4.0 and up         NaN

In [12]:
df.drop(10472, axis=0, inplace=True)


In [13]:
df.loc[10470:10475]

Category  Rating Reviews  Size     Installs  Type Price  \
10470    COMMUNICATION     3.4      49  4.0M      10,000+  Free     0   
10471  PERSONALIZATION     3.5    1042  404k     100,000+  Free     0   
10473            TOOLS     4.2  134203  4.1M  10,000,000+  Free     0   
10474    COMMUNICATION     3.4      37   14M       1,000+  Free     0   
10475            TOOLS     3.9     132  2.6M      50,000+  Free     0   

      Content Rating           Genres       Last Updated Current Ver  \
10470       Everyone    Communication  February 10, 2017         0.1   
10471       Everyone  Personalization     August 5, 2014       3.0.0   
10473       Everyone            Tools     August 7, 2018     6.06.14   
10474       Everyone    Communication  November 21, 2014     2.2.1.5   
10475       Everyone            Tools       May 17, 2017       0.0.9   

        Android Ver  
10470    2.3 and up  
10471  4.0.3 and up  
10473    4.4 and up  
10474    2.2 and up  
10475    2.3 and up

In [14]:
sorted(df['Category'].unique())

['ART_AND_DESIGN',
 'AUTO_AND_VEHICLES',
 'BEAUTY',
 'BOOKS_AND_REFERENCE',
 'BUSINESS',
 'COMICS',
 'COMMUNICATION',
 'DATING',
 'EDUCATION',
 'ENTERTAINMENT',
 'EVENTS',
 'FAMILY',
 'FINANCE',
 'FOOD_AND_DRINK',
 'GAME',
 'HEALTH_AND_FITNESS',
 'HOUSE_AND_HOME',
 'LIBRARIES_AND_DEMO',
 'LIFESTYLE',
 'MAPS_AND_NAVIGATION',
 'MEDICAL',
 'NEWS_AND_MAGAZINES',
 'PARENTING',
 'PERSONALIZATION',
 'PHOTOGRAPHY',
 'PRODUCTIVITY',
 'SHOPPING',
 'SOCIAL',
 'SPORTS',
 'TOOLS',
 'TRAVEL_AND_LOCAL',
 'VIDEO_PLAYERS',
 'WEATHER']

In [15]:
len(df['Category'].unique())

33

In [16]:
#Encoding two types.
#1.One hot encoding
#2.label encoding

In [17]:
from sklearn.preprocessing import LabelEncoder


In [18]:
l_encode = LabelEncoder()

In [19]:
df["Category"]=l_encode.fit_transform(df["Category"])

In [20]:
df.head()

Category  Rating Reviews  Size     Installs  Type Price Content Rating  \
0         0     4.1     159   19M      10,000+  Free     0       Everyone   
1         0     3.9     967   14M     500,000+  Free     0       Everyone   
2         0     4.7   87510  8.7M   5,000,000+  Free     0       Everyone   
3         0     4.5  215644   25M  50,000,000+  Free     0           Teen   
4         0     4.3     967  2.8M     100,000+  Free     0       Everyone   

                      Genres      Last Updated         Current Ver  \
0               Art & Design   January 7, 2018               1.0.0   
1  Art & Design;Pretend Play  January 15, 2018               2.0.0   
2               Art & Design    August 1, 2018               1.2.4   
3               Art & Design      June 8, 2018  Varies with device   
4    Art & Design;Creativity     June 20, 2018                 1.1   

    Android Ver  
0  4.0.3 and up  
1  4.0.3 and up  
2  4.0.3 and up  
3    4.2 and up  
4    4.4 and up

In [21]:
df["Category"].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12, 13, 15, 16, 17, 18,
       14, 11, 20, 27, 26, 24, 28, 30, 29, 23, 25, 22, 32, 31, 21, 19])

In [22]:
len(df["Category"].unique())

33

In [23]:
df.dtypes

Category            int32
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

In [24]:
df["Rating"].unique()

array([4.1, 3.9, 4.7, 4.5, 4.3, 4.4, 3.8, 4.2, 4.6, 3.2, 4. , nan, 4.8,
       4.9, 3.6, 3.7, 3.3, 3.4, 3.5, 3.1, 5. , 2.6, 3. , 1.9, 2.5, 2.8,
       2.7, 1. , 2.9, 2.3, 2.2, 1.7, 2. , 1.8, 2.4, 1.6, 2.1, 1.4, 1.5,
       1.2])

In [25]:
len(df["Rating"].unique())

40

In [26]:
rating_mean_value = df["Rating"].mean()

In [27]:
rating_mean_value

4.187876743139908

In [28]:
df["Rating"] = df["Rating"].fillna(rating_mean_value)

In [29]:
df["Rating"].isna().sum()

0

In [30]:
df.isna().sum()

Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              1
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       8
Android Ver       2
dtype: int64

In [31]:
df.dropna(inplace=True)

In [32]:
df.isna().sum()

Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64

In [33]:
df.dtypes

Category            int32
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

In [34]:
df["Reviews"].unique()

array(['159', '967', '87510', ..., '603', '1195', '398307'], dtype=object)

In [35]:
len(df["Reviews"].unique())

5999

In [36]:
df["Reviews"].dtypes

dtype('O')

In [37]:
df["Reviews"] = df["Reviews"].apply(lambda x: int(x))

In [38]:
df["Reviews"].dtypes

dtype('int64')

In [39]:
df["Reviews"].head()

0       159
1       967
2     87510
3    215644
4       967
Name: Reviews, dtype: int64

In [40]:
df.shape

(10346, 12)

In [41]:
m_count = df["Size"].apply(lambda x: x[-1])

In [42]:
m_count.unique()

array(['M', 'e', 'k'], dtype=object)

In [43]:
#Or 
pd.unique(m_count)

array(['M', 'e', 'k'], dtype=object)

In [44]:
len(m_count)

10346

In [45]:
df["Size"].unique()

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '5.5M', '17M', '39M', '31M',
       '4.2M', '7.0M', '23M', '6.0M', '6.1M', '4.6M', '9.2M', '5.2M',
       '11M', '24M', 'Varies with device', '9.4M', '15M', '10M', '1.2M',
       '26M', '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k', '3.6M',
       '5.7M', '8.6M', '2.4M', '27M', '2.7M', '2.5M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '3.7M', '22M', '7.4M', '6.4M', '3.2M', '8.2M', '9.9M',
       '4.9M', '9.5M', '5.0M', '5.9M', '13M', '73M', '6.8M', '3.5M',
       '4.0M', '2.3M', '7.2M', '2.1M', '42M', '7.3M', '9.1M', '55M',
       '23k', '6.5M', '1.5M', '7.5M', '51M', '41M', '48M', '8.5M', '46M',
       '8.3M', '4.3M', '4.7M', '3.3M', '40M', '7.8M', '8.8M', '6.6M',
       '5.1M', '61M', '66M', '79k', '8.4M', '118k', '44M', '695k', '1.6M',
     

In [46]:
df["Size"] = df["Size"].apply(lambda x: x.replace(x[-1],"") if x[-1]=="M" else x)

In [47]:
df["Size"] = df["Size"].apply(lambda x: x.replace(x[-1]," ") if x[-1]=="k" else x)

In [48]:
df['Size'][df['Size']== "Varies with device"].count()

1525

In [49]:
df['Size'] = df['Size'].apply(lambda x: x.replace("Varies with device", "0.0") if x=="Varies with device" else x)

In [50]:
df['Size'][df['Size']== "Varies with device"].count()

0

In [51]:
df['Size'] = df['Size'].apply(lambda x: float(x))

In [52]:
df['Size'].dtype

dtype('float64')

In [53]:
size_mean = df['Size'].mean()

In [54]:
size_mean

31.70654359172616

In [55]:
df['Size'][df['Size'] == 0.0].count()

1525

In [56]:
df['Size'] = df['Size'].apply(lambda x: x+size_mean if x == 0.0 else x)

In [57]:
df['Size'][df['Size'] == 0.0].count()

0

In [58]:
#Install

In [59]:
df["Installs"].unique()

array(['10,000+', '500,000+', '5,000,000+', '50,000,000+', '100,000+',
       '50,000+', '1,000,000+', '10,000,000+', '5,000+', '100,000,000+',
       '1,000,000,000+', '1,000+', '500,000,000+', '50+', '100+', '500+',
       '10+', '1+', '5+', '0+'], dtype=object)

In [60]:
df['Installs'] = df['Installs'].apply(lambda x: x.replace(",", ""))


In [61]:
df['Installs'].unique()

array(['10000+', '500000+', '5000000+', '50000000+', '100000+', '50000+',
       '1000000+', '10000000+', '5000+', '100000000+', '1000000000+',
       '1000+', '500000000+', '50+', '100+', '500+', '10+', '1+', '5+',
       '0+'], dtype=object)

In [62]:
df['Installs'] = df['Installs'].apply(lambda x: x.replace(x[-1],"") if x[-1]=="+" else x)

In [63]:
df['Installs'] = df['Installs'].apply(lambda x: int(x))

In [64]:
df['Installs'].dtype

dtype('int64')

In [65]:
df['Installs'].unique()

array([     10000,     500000,    5000000,   50000000,     100000,
            50000,    1000000,   10000000,       5000,  100000000,
       1000000000,       1000,  500000000,         50,        100,
              500,         10,          1,          5,          0],
      dtype=int64)

In [66]:
df['Installs'].isnull().sum()

0

In [67]:
#Type

In [68]:
df["Type"].unique()

array(['Free', 'Paid'], dtype=object)

In [69]:
df["Type"].isnull().sum()

0

In [70]:
df["Type"].dtype

dtype('O')

In [71]:
type_mapping = {"Free":0,"Paid":1}


In [72]:
type_mapping 

{'Free': 0, 'Paid': 1}

In [73]:
train_test_data=[df]
for dataset in train_test_data:
    dataset ["Type"] = dataset["Type"].map(type_mapping)

In [74]:
df[50:60]

Category  Rating  Reviews        Size  Installs  Type Price  \
51         1     3.8      284   57.000000    100000     0     0   
52         1     4.6    17057   31.706544   1000000     0     0   
53         1     3.9      129   35.000000    100000     0     0   
54         1     4.3      542   33.000000    100000     0     0   
55         1     4.9    10479   33.000000    100000     0     0   
56         1     4.4      805    5.600000     50000     0     0   
57         1     4.2      129   54.000000    100000     0     0   
58         1     4.0     1403  201.000000    100000     0     0   
59         1     3.9     3971    3.600000    100000     0     0   
60         1     4.6      534    5.700000     10000     0     0   

   Content Rating           Genres     Last Updated         Current Ver  \
51       Everyone  Auto & Vehicles    July 26, 2018                 3.0   
52       Everyone  Auto & Vehicles    July 30, 2018  Varies with device   
53       Everyone  Auto & Vehicles    July 26, 2018                 3.0   
54       Everyone  Auto & Vehicles    July 31, 2018                 4.0   
55       Everyone  Auto & Vehicles    July 18, 2018               1.7.1   
56       Everyone  Auto & Vehicles    July 29, 2018               2.5.1   
57       Everyone  Auto & Vehicles    July 26, 2018                 3.0   
58       Everyone  Auto & Vehicles  August 26, 2014               1.0.1   
59       Everyone  Auto & Vehicles    July 30, 2018               2.493   
60       Everyone  Auto & Vehicles     July 8, 2018               1.9.1   

           Android Ver  
51          4.1 and up  
52  Varies with device  
53          4.1 and up  
54          4.1 and up  
55          4.0 and up  
56          4.4 and up  
57          4.1 and up  
58          2.2 and up  
59          4.4 and up  
60        4.0.3 and up

In [75]:
df["Type"].unique()

array([0, 1], dtype=int64)

In [76]:
#Or 
l_encode= LabelEncoder()
df['Type'] = l_encode.fit_transform(df['Type'])
df["Type"].unique()

array([0, 1], dtype=int64)

In [77]:
#Price

In [78]:
df["Price"].unique()

array(['0', '$4.99', '$3.99', '$6.99', '$1.49', '$2.99', '$7.99', '$5.99',
       '$3.49', '$1.99', '$9.99', '$7.49', '$0.99', '$9.00', '$5.49',
       '$10.00', '$24.99', '$11.99', '$79.99', '$16.99', '$14.99',
       '$1.00', '$29.99', '$12.99', '$2.49', '$10.99', '$1.50', '$19.99',
       '$15.99', '$33.99', '$74.99', '$39.99', '$3.95', '$4.49', '$1.70',
       '$8.99', '$2.00', '$3.88', '$25.99', '$399.99', '$17.99',
       '$400.00', '$3.02', '$1.76', '$4.84', '$4.77', '$1.61', '$2.50',
       '$1.59', '$6.49', '$1.29', '$5.00', '$13.99', '$299.99', '$379.99',
       '$37.99', '$18.99', '$389.99', '$19.90', '$8.49', '$1.75',
       '$14.00', '$4.85', '$46.99', '$109.99', '$154.99', '$3.08',
       '$2.59', '$4.80', '$1.96', '$19.40', '$3.90', '$4.59', '$15.46',
       '$3.04', '$4.29', '$2.60', '$3.28', '$4.60', '$28.99', '$2.95',
       '$2.90', '$1.97', '$200.00', '$89.99', '$2.56', '$30.99', '$3.61',
       '$394.99', '$1.26', '$1.20', '$1.04'], dtype=object)

In [79]:
sorted(df["Price"].unique())

['$0.99',
 '$1.00',
 '$1.04',
 '$1.20',
 '$1.26',
 '$1.29',
 '$1.49',
 '$1.50',
 '$1.59',
 '$1.61',
 '$1.70',
 '$1.75',
 '$1.76',
 '$1.96',
 '$1.97',
 '$1.99',
 '$10.00',
 '$10.99',
 '$109.99',
 '$11.99',
 '$12.99',
 '$13.99',
 '$14.00',
 '$14.99',
 '$15.46',
 '$15.99',
 '$154.99',
 '$16.99',
 '$17.99',
 '$18.99',
 '$19.40',
 '$19.90',
 '$19.99',
 '$2.00',
 '$2.49',
 '$2.50',
 '$2.56',
 '$2.59',
 '$2.60',
 '$2.90',
 '$2.95',
 '$2.99',
 '$200.00',
 '$24.99',
 '$25.99',
 '$28.99',
 '$29.99',
 '$299.99',
 '$3.02',
 '$3.04',
 '$3.08',
 '$3.28',
 '$3.49',
 '$3.61',
 '$3.88',
 '$3.90',
 '$3.95',
 '$3.99',
 '$30.99',
 '$33.99',
 '$37.99',
 '$379.99',
 '$389.99',
 '$39.99',
 '$394.99',
 '$399.99',
 '$4.29',
 '$4.49',
 '$4.59',
 '$4.60',
 '$4.77',
 '$4.80',
 '$4.84',
 '$4.85',
 '$4.99',
 '$400.00',
 '$46.99',
 '$5.00',
 '$5.49',
 '$5.99',
 '$6.49',
 '$6.99',
 '$7.49',
 '$7.99',
 '$74.99',
 '$79.99',
 '$8.49',
 '$8.99',
 '$89.99',
 '$9.00',
 '$9.99',
 '0']

In [80]:
df['Price'] = df['Price'].apply(lambda x: x.replace("$", " "))

In [81]:
df['Price'].unique()

array(['0', ' 4.99', ' 3.99', ' 6.99', ' 1.49', ' 2.99', ' 7.99', ' 5.99',
       ' 3.49', ' 1.99', ' 9.99', ' 7.49', ' 0.99', ' 9.00', ' 5.49',
       ' 10.00', ' 24.99', ' 11.99', ' 79.99', ' 16.99', ' 14.99',
       ' 1.00', ' 29.99', ' 12.99', ' 2.49', ' 10.99', ' 1.50', ' 19.99',
       ' 15.99', ' 33.99', ' 74.99', ' 39.99', ' 3.95', ' 4.49', ' 1.70',
       ' 8.99', ' 2.00', ' 3.88', ' 25.99', ' 399.99', ' 17.99',
       ' 400.00', ' 3.02', ' 1.76', ' 4.84', ' 4.77', ' 1.61', ' 2.50',
       ' 1.59', ' 6.49', ' 1.29', ' 5.00', ' 13.99', ' 299.99', ' 379.99',
       ' 37.99', ' 18.99', ' 389.99', ' 19.90', ' 8.49', ' 1.75',
       ' 14.00', ' 4.85', ' 46.99', ' 109.99', ' 154.99', ' 3.08',
       ' 2.59', ' 4.80', ' 1.96', ' 19.40', ' 3.90', ' 4.59', ' 15.46',
       ' 3.04', ' 4.29', ' 2.60', ' 3.28', ' 4.60', ' 28.99', ' 2.95',
       ' 2.90', ' 1.97', ' 200.00', ' 89.99', ' 2.56', ' 30.99', ' 3.61',
       ' 394.99', ' 1.26', ' 1.20', ' 1.04'], dtype=object)

In [82]:
df["Price"]= df["Price"].apply(lambda x: float(x))

In [83]:
df["Price"].dtype

dtype('float64')

In [84]:
df["Price"].isnull().sum()

0

In [85]:
df.head()

Category  Rating  Reviews  Size  Installs  Type  Price Content Rating  \
0         0     4.1      159  19.0     10000     0    0.0       Everyone   
1         0     3.9      967  14.0    500000     0    0.0       Everyone   
2         0     4.7    87510   8.7   5000000     0    0.0       Everyone   
3         0     4.5   215644  25.0  50000000     0    0.0           Teen   
4         0     4.3      967   2.8    100000     0    0.0       Everyone   

                      Genres      Last Updated         Current Ver  \
0               Art & Design   January 7, 2018               1.0.0   
1  Art & Design;Pretend Play  January 15, 2018               2.0.0   
2               Art & Design    August 1, 2018               1.2.4   
3               Art & Design      June 8, 2018  Varies with device   
4    Art & Design;Creativity     June 20, 2018                 1.1   

    Android Ver  
0  4.0.3 and up  
1  4.0.3 and up  
2  4.0.3 and up  
3    4.2 and up  
4    4.4 and up

In [86]:
# Content Rating

In [87]:
df["Content Rating"].unique()

array(['Everyone', 'Teen', 'Everyone 10+', 'Mature 17+',
       'Adults only 18+', 'Unrated'], dtype=object)

In [88]:
df["Content Rating"].isna().sum()

0

In [89]:
l_encode= LabelEncoder()

In [90]:
df["Content Rating"]= l_encode.fit_transform(df["Content Rating"])

In [91]:
print(df["Content Rating"].unique())

[1 4 2 3 0 5]


In [92]:
sorted(df["Content Rating"].unique())

[0, 1, 2, 3, 4, 5]

In [93]:
#Genres

In [94]:
df.columns

Index(['Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type', 'Price',
       'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [95]:
df["Genres"].unique()

array(['Art & Design', 'Art & Design;Pretend Play',
       'Art & Design;Creativity', 'Art & Design;Action & Adventure',
       'Auto & Vehicles', 'Beauty', 'Books & Reference', 'Business',
       'Comics', 'Comics;Creativity', 'Communication', 'Dating',
       'Education;Education', 'Education', 'Education;Creativity',
       'Education;Music & Video', 'Education;Action & Adventure',
       'Education;Pretend Play', 'Education;Brain Games', 'Entertainment',
       'Entertainment;Music & Video', 'Entertainment;Brain Games',
       'Entertainment;Creativity', 'Events', 'Finance', 'Food & Drink',
       'Health & Fitness', 'House & Home', 'Libraries & Demo',
       'Lifestyle', 'Lifestyle;Pretend Play',
       'Adventure;Action & Adventure', 'Arcade', 'Casual', 'Card',
       'Casual;Pretend Play', 'Action', 'Strategy', 'Puzzle', 'Sports',
       'Music', 'Word', 'Racing', 'Casual;Creativity',
       'Casual;Action & Adventure', 'Simulation', 'Adventure', 'Board',
       'Trivia', 'Role 

In [96]:
sorted(df["Genres"].unique())

['Action',
 'Action;Action & Adventure',
 'Adventure',
 'Adventure;Action & Adventure',
 'Adventure;Brain Games',
 'Adventure;Education',
 'Arcade',
 'Arcade;Action & Adventure',
 'Arcade;Pretend Play',
 'Art & Design',
 'Art & Design;Action & Adventure',
 'Art & Design;Creativity',
 'Art & Design;Pretend Play',
 'Auto & Vehicles',
 'Beauty',
 'Board',
 'Board;Action & Adventure',
 'Board;Brain Games',
 'Board;Pretend Play',
 'Books & Reference',
 'Books & Reference;Creativity',
 'Books & Reference;Education',
 'Business',
 'Card',
 'Card;Action & Adventure',
 'Card;Brain Games',
 'Casino',
 'Casual',
 'Casual;Action & Adventure',
 'Casual;Brain Games',
 'Casual;Creativity',
 'Casual;Education',
 'Casual;Music & Video',
 'Casual;Pretend Play',
 'Comics',
 'Comics;Creativity',
 'Communication',
 'Communication;Creativity',
 'Dating',
 'Education',
 'Education;Action & Adventure',
 'Education;Brain Games',
 'Education;Creativity',
 'Education;Education',
 'Education;Music & Video',
 'Edu

In [97]:
len(df["Genres"].unique())

119

In [98]:
l_encode= LabelEncoder()
df["Genres"] = l_encode.fit_transform(df["Genres"])
df["Genres"].unique()

array([  9,  12,  11,  10,  13,  14,  19,  22,  34,  35,  36,  38,  43,
        39,  42,  44,  40,  45,  41,  52,  57,  54,  55,  59,  60,  61,
        62,  65,  66,  67,  69,   3,   6,  27,  23,  33,   0, 104,  83,
       102,  72, 118,  88,  30,  28,  97,   2,  15, 112,  91,  99,   1,
        29,  98,  49,  85,  50,  25,  48,  51,  56,  31,  74,  89,   8,
        92, 100,  86, 103,  47,   7,  53,  84, 105,  73,  64,   5,  17,
        16,  18,  32,  95,  58, 115,  24,  71, 101,  96,  81, 110, 111,
       108, 109,  80,  82,  76,  79,  78,  77, 117, 114, 116,  75,  70,
        63,  46,  26,   4, 113,  68,  20,  21,  87,  94,  93, 107,  90,
        37, 106])

In [99]:
sorted(df["Genres"].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118]

In [100]:
df

Category    Rating  Reviews       Size  Installs  Type  Price  \
0             0  4.100000      159  19.000000     10000     0    0.0   
1             0  3.900000      967  14.000000    500000     0    0.0   
2             0  4.700000    87510   8.700000   5000000     0    0.0   
3             0  4.500000   215644  25.000000  50000000     0    0.0   
4             0  4.300000      967   2.800000    100000     0    0.0   
...         ...       ...      ...        ...       ...   ...    ...   
10836        11  4.500000       38  53.000000      5000     0    0.0   
10837        11  5.000000        4   3.600000       100     0    0.0   
10838        20  4.187877        3   9.500000      1000     0    0.0   
10839         3  4.500000      114  31.706544      1000     0    0.0   
10840        18  4.500000   398307  19.000000  10000000     0    0.0   

       Content Rating  Genres      Last Updated         Current Ver  \
0                   1       9   January 7, 2018               1.0.0   
1                   1      12  January 15, 2018               2.0.0   
2                   1       9    August 1, 2018               1.2.4   
3                   4       9      June 8, 2018  Varies with device   
4                   1      11     June 20, 2018                 1.1   
...               ...     ...               ...                 ...   
10836               1      39     July 25, 2017                1.48   
10837               1      39      July 6, 2018                 1.0   
10838               1      71  January 20, 2017                 1.0   
10839               3      19  January 19, 2015  Varies with device   
10840               1      67     July 25, 2018  Varies with device   

              Android Ver  
0            4.0.3 and up  
1            4.0.3 and up  
2            4.0.3 and up  
3              4.2 and up  
4              4.4 and up  
...                   ...  
10836          4.1 and up  
10837          4.1 and up  
10838          2.2 and up  
10839  Varies with device  
10840  Varies with device  

[10346 rows x 12 columns]

In [101]:
df["Last Updated"].unique()

array(['January 7, 2018', 'January 15, 2018', 'August 1, 2018', ...,
       'January 20, 2014', 'February 16, 2014', 'March 23, 2014'],
      dtype=object)

In [113]:
df["Last Updated"]=df["Last Updated"].apply(lambda x: x.replace(x[:-4], ""))

AttributeError: 'int' object has no attribute 'replace'

In [114]:
df["Last Updated"].unique()

array([2018, 2017, 2014, 2016, 2015, 2013, 2012, 2011, 2010], dtype=int64)

In [104]:
df["Last Updated"]=df["Last Updated"].apply(lambda x: int(x))

In [105]:
df["Last Updated"].dtype

dtype('int64')

In [106]:
print(df["Last Updated"].unique())

[2018 2017 2014 2016 2015 2013 2012 2011 2010]


In [107]:
#Problem


In [111]:
#Last Updated
train_test_data=[df]
for dataset in train_test_data:
    dataset["Last Updated"]=dataset["Last Updated"].str.extract('([A-za-z]+)', expand=False)

AttributeError: Can only use .str accessor with string values!

In [ ]:
df.head()

In [ ]:
df["Last Updated"].unique()

In [ ]:
#Current Ver

In [ ]:
df["Current Ver"].unique()

In [ ]:
print(df["Current Ver"].unique())

In [ ]:
sorted(df["Current Ver"].unique())

In [ ]:
len(sorted(df["Current Ver"].unique()))

In [ ]:
len(sorted(df["Current Ver"].unique()))

In [ ]:
df["Current Ver"].isnull().sum()

In [ ]:

#Android Ver
sorted(df["Android Ver"].unique())

In [ ]:
len(df["Android Ver"].unique())

In [ ]:
df['Android Ver'][df['Android Ver']== "Varies with device"].count()